# Được cấp phép bởi Hiệp hội Phần mềm Apache (ASF) theo một
# hoặc nhiều thỏa thuận cấp phép nhà đóng góp. Xem tệp NOTICE
# đi kèm với tác phẩm này để biết thêm thông tin
# liên quan đến bản quyền sở hữu. ASF cấp phép tệp này
# cho bạn theo Giấy phép Apache, Phiên bản 2.0
# ("Giấy phép"); bạn không được sử dụng tệp này trừ khi
# tuân thủ đúng Giấy phép. Bạn có thể lấy một bản sao của Giấy phép tại:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Trừ khi được yêu cầu bởi luật hiện hành hoặc được chấp thuận bằng văn bản,
# phần mềm được phân phối theo Giấy phép được phân phối trên cơ sở "NGUYÊN TRẠNG",
# KHÔNG CÓ BẤT KỲ SỰ BẢO ĐẢM HOẶC ĐIỀU KIỆN NÀO, dù là diễn giải hay hàm ý.
# Xem Giấy phép để biết ngôn ngữ cụ thể quy định về các quyền hạn và
# giới hạn theo Giấy phép.
#

# Cấu hình cụm (cluster) Airflow cơ bản cho CeleryExecutor kết hợp với Redis và PostgreSQL.
#
# CẢNH BÁO: Cấu hình này phục vụ cho môi trường phát triển cục bộ (local development). Không sử dụng cấu hình này trên môi trường triển khai thực tế (production).
#
# Cấu hình này hỗ trợ việc thiết lập cơ bản bằng các biến môi trường (environment variables) hoặc qua tệp .env
# Các biến môi trường sau đây được hỗ trợ:
#
# AIRFLOW_IMAGE_NAME           - Tên Docker image được dùng để chạy Airflow.
#                                Mặc định: apache/airflow:2.9.2
# AIRFLOW_UID                  - Mã định danh người dùng (User ID) trong các container Airflow.
#                                Mặc định: 50000
# AIRFLOW_PROJ_DIR             - Đường dẫn gốc (base path) mà tất cả các tệp sẽ được gắn hằng số ánh xạ (volume).
#                                Mặc định: .
# Những cấu hình này chủ yếu hữu ích trong trường hợp kiểm thử độc lập/chạy Airflow ở chế độ thử nghiệm
#
# _AIRFLOW_WWW_USER_USERNAME   - Tên người dùng cho tài khoản quản trị viên (nếu được yêu cầu).
#                                Mặc định: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Mật khẩu cho tài khoản quản trị viên (nếu được yêu cầu).
#                                Mặc định: airflow
# _PIP_ADDITIONAL_REQUIREMENTS - Các gói thư viện PIP bổ sung cần cài đặt khi khởi chạy tất cả các container.
#                                CHỈ sử dụng tùy chọn này cho các kiểm tra nhanh. Việc cài đặt các gói thư viện
#                                lúc khởi chạy container sẽ được thực hiện MỖI LẦN dịch vụ khởi động lại.
#                                Phương pháp tối ưu hơn là xây dựng một image tùy chỉnh hoặc mở rộng image chính thức
#                                như được mô tả tại https://airflow.apache.org/docs/docker-stack/build.html.
#                                Mặc định: ''
#
# Bạn có thể tùy chỉnh tệp này để phù hợp với nhu cầu của mình.
---
x-airflow-common:
  &airflow-common
  # Sử dụng image tùy chỉnh được xây dựng dựa trên image Airflow mặc định (hiện tại; Mặc định: apache/airflow:2.9.2)
  # Image được lưu trữ trên Docker Hub
  image: ${DOCKERHUB_NAMESPACE}/${DOCKERHUB_REPOSITORY}:${IMAGE_TAG}
  # Sử dụng tệp .env để đọc các tham số kết nối và biến môi trường - TẮT TÙY CHỌN NÀY KHỦNG DÙNG GITHUB ACTIONS
  env_file:
    - .env
  environment:
    &airflow-common-env
    # Thiết lập bộ thực thi (executor) thành CeleryExecutor 
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    # Sử dụng SQLAlchemy để kết nối với cơ sở dữ liệu cơ sở (metadata database) Postgres của Airflow thông qua trình điều khiển (driver) psycopg2
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${METADATA_DATABASE_USERNAME}:${METADATA_DATABASE_PASSWORD}@${POSTGRES_CONN_HOST}:${POSTGRES_CONN_PORT}/${METADATA_DATABASE_NAME}
    # Cơ sở dữ liệu Postgres backend dùng để lưu trữ kết quả của các tác vụ (task) được thực thi bởi các worker
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${CELERY_BACKEND_USERNAME}:${CELERY_BACKEND_PASSWORD}@${POSTGRES_CONN_HOST}:${POSTGRES_CONN_PORT}/${CELERY_BACKEND_NAME}
    # URL kết nối tới Redis message broker - xử lý giao tiếp và phân phối tác vụ giữa scheduler (bộ lập lịch) và các worker
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    # Khóa Fernet để mã hóa dữ liệu nhạy cảm
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    # Các DAG mới tạo sẽ ở trạng thái tạm dừng (paused) theo mặc định
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    # Đặt thành false để loại bỏ các DAG mẫu mặc định - https://stackoverflow.com/questions/43410836/how-to-remove-default-example-dags-in-airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # Cấu hình các phương thức xác thực API. Cho phép xác thực cơ bản (basic) & dựa trên phiên làm việc (session)
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    # Bật kiểm tra trạng thái hoạt động (health check) cho bộ lập lịch (scheduler)
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    # Thiết lập Kết nối (Connections) và Biến (Variables) trong Airflow
    # LƯU Ý 1: Các thiết lập này sẽ không hiển thị trên Giao diện người dùng (Airflow UI) hoặc khi dùng lệnh liệt kê connections/variables 
    # Tuy nhiên, các hàm như Variable.get() vẫn hoạt động bình thường theo tài liệu của Airflow miễn là
    # tên biến bắt đầu bằng AIRFLOW_VAR_- https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#storing-variables-in-environment-variables
    # LƯU Ý 2: Dấu gạch dưới đơn được Airflow sử dụng để đọc các connection/variable
    # Kết nối có thể được viết dưới dạng chuỗi định danh tài nguyên URI: 
    # AIRFLOW_CONN_{CONN_ID}='my-conn-type://login:password@host:port/schema?param1=val1&param2=val2'
    # Kết nối tới cơ sở dữ liệu PostgreSQL bên ngoài cần thiết để lưu trữ dữ liệu từ tiến trình ELT
    AIRFLOW_CONN_POSTGRES_DB_YT_ELT: 'postgresql://${ELT_DATABASE_USERNAME}:${ELT_DATABASE_PASSWORD}@${POSTGRES_CONN_HOST}:${POSTGRES_CONN_PORT}/${ELT_DATABASE_NAME}'
    # Biến môi trường có thể được viết như sau: 
    # AIRFLOW_VAR_{VARIABLE_NAME}
    AIRFLOW_VAR_API_KEY: ${API_KEY}
    AIRFLOW_VAR_CHANNEL_HANDLE: ${CHANNEL_HANDLE}
    # Các biến môi trường của cơ sở dữ liệu Postgres - Cần thiết cho các kiểm thử tích hợp (integration tests) và kiểm thử chất lượng dữ liệu (data quality tests)
    ELT_DATABASE_NAME: ${ELT_DATABASE_NAME}
    ELT_DATABASE_USERNAME: ${ELT_DATABASE_USERNAME}
    ELT_DATABASE_PASSWORD: ${ELT_DATABASE_PASSWORD}
    POSTGRES_CONN_HOST: ${POSTGRES_CONN_HOST}
    POSTGRES_CONN_PORT: ${POSTGRES_CONN_PORT}
  volumes:
    - ./config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./include:/opt/airflow/include
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests
  user: "${AIRFLOW_UID}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    container_name: postgres
    image: postgres:13
    # Sử dụng tệp .env để đọc các tham số kết nối - TẮT TÙY CHỌN NÀY KHI DÙNG GITHUB ACTIONS
    env_file:
      - .env
    # Các biến môi trường sau POSTGRES_PASSWORD cần thiết cho luồng công việc CI/CD - BẬT TẤT CẢ TÙY CHỌN NÀY KHI DÙNG GITHUB ACTIONS
    environment:
      - POSTGRES_USER=${POSTGRES_CONN_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_CONN_PASSWORD}
    #   - METADATA_DATABASE_NAME=${METADATA_DATABASE_NAME}
    #   - METADATA_DATABASE_USERNAME=${METADATA_DATABASE_USERNAME}
    #   - METADATA_DATABASE_PASSWORD=${METADATA_DATABASE_PASSWORD}
    #   - ELT_DATABASE_NAME=${ELT_DATABASE_NAME}
    #   - ELT_DATABASE_USERNAME=${ELT_DATABASE_USERNAME}
    #   - ELT_DATABASE_PASSWORD=${ELT_DATABASE_PASSWORD}
    #   - CELERY_BACKEND_NAME=${CELERY_BACKEND_NAME}
    #   - CELERY_BACKEND_USERNAME=${CELERY_BACKEND_USERNAME}
    #   - CELERY_BACKEND_PASSWORD=${CELERY_BACKEND_PASSWORD}
    #   - POSTGRES_CONN_HOST=${POSTGRES_CONN_HOST}
    #   - POSTGRES_CONN_PORT=${POSTGRES_CONN_PORT}
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    # Kiểm tra kết nối tới 1 trong 3 cơ sở dữ liệu, trong trường hợp này là metadata db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_CONN_USERNAME}", "-d", "${METADATA_DATABASE_NAME}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    # Redis bị giới hạn ở phiên bản 7.2-bookworm do sự thay đổi về bản quyền phần mềm
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    container_name: airflow-worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Bắt buộc để xử lý việc tắt mượt mà (warm shutdown) các celery worker một cách chính xác
      # Xem thêm tại https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  # airflow-triggerer:
  #   <<: *airflow-common
  #   command: triggerer
  #   container_name: airflow-triggerer
  #   healthcheck:
  #     test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 30s
  #   restart: always
  #   depends_on:
  #     <<: *airflow-common-depends-on
  #     airflow-init:
  #       condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    container_name: airflow-init
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mCẢNH BÁO!!!: Chưa thiết lập AIRFLOW_UID!\e[0m"
          echo "Nếu bạn đang dùng Linux, bạn NÊN làm theo hướng dẫn bên dưới để thiết lập "
          echo "biến môi trường AIRFLOW_UID, nếu không các tệp sẽ thuộc quyền sở hữu của user root."
          echo "Đối với các hệ điều hành khác, bạn có thể loại bỏ cảnh báo này bằng cách tạo tệp .env thủ công:"
          echo "    Xem: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mCẢNH BÁO!!!: Không đủ bộ nhớ RAM khả dụng cho Docker.\e[0m"
          echo "Yêu cầu tối thiểu 4GB RAM. Bạn hiện có $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mCẢNH BÁO!!!: Không đủ số lượng CPU khả dụng cho Docker.\e[0m"
          echo "Khuyến nghị tối thiểu 2 CPUs. Bạn hiện có $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mCẢNH BÁO!!!: Không đủ dung lượng đĩa trống khả dụng cho Docker.\e[0m"
          echo "Khuyến nghị tối thiểu 10 GBs. Bạn hiện có $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mCẢNH BÁO!!!: Bạn không có đủ tài nguyên phần cứng để chạy Airflow (sẽ xem chi tiết ở trên)!\e[0m"
          echo "Vui lòng làm theo hướng dẫn để tăng dung lượng tài nguyên khả dụng:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/dags /sources/data /sources/include /sources/logs /sources/tests
        chown -R "${AIRFLOW_UID}:0" /sources/{dags,data,include,logs,tests}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_USER_PASSWORD}
    user: "0:0"
    volumes:
      - .:/sources

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Giải pháp tạm thời (workaround) cho sự cố entrypoint. Xem tại: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow

  # # Bạn có thể kích hoạt Flower bằng cách thêm tùy chọn "--profile flower", ví dụ: docker-compose --profile flower up
  # # hoặc chỉ định trực tiếp trên dòng lệnh, ví dụ: docker-compose up flower.
  # # Xem thêm tại: https://docs.docker.com/compose/profiles/
  # flower:
  #   <<: *airflow-common
  #   command: celery flower
  #   container_name: airflow-celery-flower
  #   profiles:
  #     - flower
  #   ports:
  #     - "5555:5555"
  #   healthcheck:
  #     test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 30s
  #   restart: always
  #   depends_on:
  #     <<: *airflow-common-depends-on
  #     airflow-init:
  #       condition: service_completed_successfully

volumes:
  postgres-db-volume: